classes: threecars
finetune_from: threecars_pretrained_lr
batch_size: 8
workers: 4
niter: 500
lr: 1.0e-06
beta1: 0.9
cuda: true
pretrained: false
seed: 0
fraction: null
stylemix: false
coarsemix: true
stylepca: false
coarsepca: false
stylerand: false
coarserand: false
outf: classifiers/threecars_finetuned_WM_lr
