classes: catface
finetune_from: catface_pretrained_lr
batch_size: 8
workers: 4
niter: 500
lr: 1.0e-06
beta1: 0.9
cuda: true
pretrained: false
seed: 3
fraction: null
stylemix: false
coarsemix: false
stylepca: false
coarsepca: false
stylepcafixed: false
coarsepcafixed: true
stylerand: false
coarserand: false
outf: classifiers/catface_finetuned_WPmf_lr_seed3
